steps:
  - id: 'build'
    name: 'gcr.io/cloud-builders/mvn'
    args: [
        'clean',
        'package',
        '-Dmaven.test.skip=true'
    ]
  - id: 'docker build'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/$COMMIT_SHA', '.' ]
  - id: 'docker push'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-C', 'docker push gcr.io/$PROJECT_ID/$COMMIT_SHA']
