steps:
  - id: 'build'
    name: 'gcr.io/cloud-builders/mvn'
    args: [
        'clean',
        'package',
        '-Dmaven.test.skip=true'
    ]
  - name: 'ubuntu'
    entrypoint: 'vi'
    args: ['Dockerfile']
  - id: 'docker build'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/$_PROJECT_NAME:$COMMIT_SHA', '.' ]
