steps:
#  프로젝트 build (*.jar 파일 생성)
  - id: 'build'
    name: 'gcr.io/cloud-builders/mvn'
    args: [
        'clean',
        'package',
        '-Dmaven.test.skip=true'
    ]

#    Docker image 생성 (Dockerfile 에 작성된 환경을 image)
#    Docker image name format : [Registry URL]/[사용자 ID]/[이미지명]:[tag]
  - id: 'docker build'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA', '.' ]

#    Docker image list
  - id: 'docker image list'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'images']

#    Docker registry 에 push
  - id: 'publish'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA']

#   Deploy to GKE
  - id : 'deploy'
    name: 'gcr.io/cloud-builders/gke-deploy:stable'
    args:
      - run
      - --image=gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA
      - --location=$${CLOUDSDK_COMPUTE_ZONE}
      - --cluster=$${CLOUDSDK_CONTAINER_CLUSTER}
options:
  env:
    - CLOUDSDK_COMPUTE_ZONE = asia-northeast1-a
    - CLOUDSDK_CONTAINER_CLUSTER = uplus-poc-test
timeout: 1600s